### ISSUE TITLE
PM Warning is not working

### ISSUE THREAD

**Issue by gn36** [phpbb-de/phpbb-ext-contact-form#2]
The PM warning seems to be non-functional.

**Comment by gn36** [comment]
The PM warning is working, but will only show on page reload, not if new recipients are added using ajax.

**Comment by Crizz0** [comment]
Are we able to use a AJAX callback, too, to display the warning?

**Comment by gn36** [comment]
Hm, correction. Network profile seems to show a complete page reload. But only after the second reload it shows. Maybe the php event used is too early in the chain.

Whether we can hijack an ajax request is nevertheless an interesting question...

**Comment by Elsensee** [comment]
You forgot to check the posted array `add_u` in your event listener for new users.
The comment suggests you did this but there is no code below that, so I assume it somehow was removed for any reason?

**Comment by gn36** [comment]
hm that seems right. Corrected.

**Comment by Elsensee** [comment]
Every event in that file is just really bad. They all miss the recipient list which, IMHO, is the most important element there. I don't know why that was left out...
